SELECT *FROM CUSTOMERS

--CUSTOMERS TABLOSUNDAN ADI 'A' HARFÝ ÝLE BAÞLAYAN KÝÞÝLERÝ ÇEKEN SORGU
SELECT *FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%' --A% BAÞ HARFÝ A OLAN,%A SON HARFÝ A OLAN


--CUSTOMERS TABLOSUNDAN ADI 'A' HARFÝ ÝLE BAÞLAYAN ERKEK MÜÞTERÝLERÝ ÇEKEN SORGU
SELECT *FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%' AND GENDER='E'


--1990 VE 1995 YILLARI ARASINDA DOÐAN MÜÞTERÝLERÝ ÇEKÝN. 1990 VE 1995 DAHÝL
SELECT *FROM CUSTOMERS WHERE BIRTHDATE>='1990-01-01' AND BIRTHDATE<='1995-12-31'
SELECT *FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '1990-01-01' AND '1995-12-31'
SELECT *FROM CUSTOMERS WHERE YEAR(BIRTHDATE) BETWEEN 1990 AND 1995

--ÝSTANBULDA YAÞAYAN KÝÞÝLERÝ JOÝN KULLANARAK GETÝREN SORGU
--(customers ve cýtýes tablosu arasýnda baðlantý var)
SELECT *FROM CUSTOMERS C INNER JOIN CITIES CT ON C.CITYID=CT.ID WHERE CT.CITY='ÝSTANBUL'

--ÝSTANBULDA YAÞAYAN KÝÞÝLERÝ SUBQUERY KULLANARAK GETÝREN SORGU
SELECT( SELECT CITY FROM CITIES WHERE ID=C.CITYID), *FROM CUSTOMERS C